# Generated by Django 2.2.16 on 2023-02-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230204_1202'),
        ('cart', '0003_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='recipes',
        ),
        migrations.AddField(
            model_name='cart',
            name='recipes',
            field=models.ManyToManyField(through='cart.CartRecipes', to='recipes.Recipe',
                                         verbose_name='Recipes in cart'),
        ),
        migrations.AddField(
            model_name='cartrecipes',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='cartrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='recipes.Recipe'),
        ),
    ]
