# Generated by Django 2.2.16 on 2023-02-17 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('recipes__name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Ingredient name')),
                ('measurement_unit', models.CharField(max_length=16, verbose_name='Measurement unit')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Recipe name')),
                ('text', models.TextField(blank=True, verbose_name='Recipe description')),
                ('image', models.ImageField(blank=True, upload_to='recipes_photos/', verbose_name='Recipe photo')),
                ('cooking_time', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=1440)], verbose_name='cooking time')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish date')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Recipe tag')),
                ('slug', models.SlugField(max_length=16, unique=True, verbose_name='Recipe tag slug')),
                ('color', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Color format error (#AABBCC or #ABC)', regex='^#(0-9a-fA-F]{3,6}$')], verbose_name='Tag color')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=10000)], verbose_name='amount of ingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.Ingredient', verbose_name='Ingredient with measurement unit')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Recipe', verbose_name='Recipe')),
            ],
            options={
                'ordering': ('ingredient__name',),
            },
        ),
    ]
