# Generated by Django 2.2.16 on 2023-01-25 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Recipe author'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.Tag'),
        ),
        migrations.AddField(
            model_name='ingredientsunits',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_with_unit', to='recipes.Ingredient', verbose_name='Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientsunits',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_with_unit', to='recipes.IngredientUnit', verbose_name='Ingredient measurement unit'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ManyToManyField(related_name='ingredients', through='recipes.IngredientsUnits', to='recipes.IngredientUnit', verbose_name='Ingredient measurement unit'),
        ),
    ]
