# Generated by Django 2.2.16 on 2023-02-17 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230217_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Color format error (#AABBCC or #ABC)', regex='^#[0-9a-fA-F]{3,6}$')], verbose_name='Tag color'),
        ),
    ]
