# Generated by Django 2.2.16 on 2023-02-01 10:21

import django.core.validators
from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230201_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(null=True, validators=[recipes.models.validate_more_or_equal_one], verbose_name='cooking time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Recipe name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Color format error (#AABBCC)', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Tag color'),
        ),
    ]
