# Generated by Django 2.2.16 on 2023-02-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230201_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientsUnits',
            new_name='IngredientWithUnit',
        ),
    ]
