# Generated by Django 2.2.16 on 2023-02-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230202_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inredients', to='recipes.Recipe', verbose_name='Recipe'),
        ),
    ]
