# Generated by Django 2.2.16 on 2023-02-01 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230201_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username format error. Letters, digits and @/./+/-/_ only.', regex='^[\\w.@+-]+\\Z')], verbose_name='User name'),
        ),
    ]
